---
name: tomcat
services:
  tomcat_stack:
    image: docker.arvancloud.ir/tomcat:8.0
    ports:
      - "8080:8080"
    deploy:
      mode: replicated
      replicas: 5
      placement:
        constraints: [node.role == worker]
        max_replicas_per_node: 3
      resources:
        limits:
          cpus: "0.50"
          memory: 512M
      update_config:
        parallelism: 2
        delay: 10s
        order: start-first
      restart_policy:
        condition: on-failure
        delay: 5s

