---
- name: Prepare server
  become: true
  ansible.builtin.import_tasks:
    file: prepare.yaml
  tags: prepare

- name: Configure DNS
  become: true
  ansible.builtin.import_tasks:
    file: dns.yaml
  tags: [prepare, dns]

- name: Hardening
  become: true
  ansible.builtin.import_tasks:
    file: hardening.yaml
  tags: hardening
