auditd:
  apply_audit_rules: "yes"
  action_mail_acct: root
  admin_space_left_action: suspend
  disk_error_action: suspend
  disk_full_action: suspend
  max_log_file: 8
  max_log_file_action: keep_logs
  mode: 1
  num_logs: 5
  space_left: 75
  space_left_action: email
  grub_backlog_cmdline: audit_backlog_limit=8192
  grub_cmdline: audit=1

ssh:
  port: "{{ ansible_port }}"
  allowed_users: "{{ ansible_user }}"
  allowed_groups: "{{ ansible_user }}"
  permit_root_login: without-password
  user_session_timeout: 600

iptables:
  allowed_tcp_ports:
    - 22
    - 80
    - 443
