---
wordpress:
  root: /etc/wordpress
  subdomain: wp
  db_name: wordpress
  db_user: parsa

# not defined as wordpress.domain to prevent infinite loop
wordpress_domain: "{{ wordpress.subdomain }}.{{ root_domain }}"
